### ISSUE TITLE
core 2.4.2 build error

### ISSUE THREAD

**Issue by marcobrianza** [tzapu/WiFiManager#685]
#### Hardware
WiFimanager Branch/Release:  Development

Esp8266: 
Hardware:			Wemos D1 Pro
Core Version:      	2.4.2

### Description

after upgrading the esp8266 core from 2.4.1 to 2.4.2 build fails.

### Settings in IDE

Module:  			Wemos D1 Pro

### Debug Messages

/var/folders/lv/r8c0j99n56g8htmghf4qbbyc0000gn/T/arduino_build_266395/libraries/WiFiManager-master/WiFiManager.cpp.o: In function `WiFiManager::waitForConnectResult()':
/Applications/Arduino.app/Contents/Java/portable/sketchbook/libraries/WiFiManager-master/WiFiManager.cpp:759: undefined reference to `WPS_is_unavailable_in_this_configuration__Please_check_FAQ_or_board_generator_tool'
/var/folders/lv/r8c0j99n56g8htmghf4qbbyc0000gn/T/arduino_build_266395/libraries/WiFiManager-master/WiFiManager.cpp.o: In function `WiFiManager::startWPS()':
/Applications/Arduino.app/Contents/Java/portable/sketchbook/libraries/WiFiManager-master/WiFiManager.cpp:759: undefined reference to `WPS_is_unavailable_in_this_configuration__Please_check_FAQ_or_board_generator_tool'
collect2: error: ld returned 1 exit status

**Comment by liebman** [comment]
Is that with a recent checkout if the development branch?  This should be fixed with https://github.com/tzapu/WiFiManager/pull/645 - merged about a month ago.

**Comment by marcobrianza** [comment]
thank you @liebman I can confirm that the development branch builds without errors. 
The release available from library manger had issues so I switched to the github version but initially I used the master.  I think it is the time to make a new official release :-)

**Comment by tablatronix** [comment]
Hotfixes contains critical fixes to master

**Comment by marcobrianza** [comment]
Is there a plan to make a new release so it is available with Arduino library manager?

**Comment by marcobrianza** [comment]
I can do some testing after mid August if needed.
for beta versions have a look at ArduinoJson
https://github.com/bblanchon/ArduinoJson/releases
