### ISSUE TITLE
error: field '_server' has incomplete type

### ISSUE THREAD

**Issue by roccomuso** [tzapu/WiFiManager#17]
This is my Sketch:

    #include <EEPROM.h>
    #include <WiFiClient.h>
    #include <ESP8266WebServer.h>
    #include <DNSServer.h>
    #include <WiFiManager.h>
    
     
    void setup() {
      // put your setup code here, to run once:
    
    }
    
    void loop() {
      // put your main code here, to run repeatedly:
    
    }

My error during compiling process:

    Arduino:1.6.6 (Windows 10), Scheda:"NodeMCU 1.0 (ESP-12E Module), 80 MHz, Serial, 115200, 4M (3M SPIFFS)"

    In file included from C:\Users\Rocco\Documents\Arduino\hello_world\hello_world.ino:4:0:

     C:\Users\Rocco\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.0.0\libraries\ESP8266WebServer\src/ESP8266WebServer.h:143:15: error: field '_server' has incomplete type

       WiFiServer  _server;

                   ^

    exit status 1

The weird thing is that sometime I got the error and sometime I doesn't. o.O

**Comment by tzapu** [comment]
hi, are you using the latest staging release of the arduino esp8266 core?

**Comment by roccomuso** [comment]
@tzapu I'm using the last 2.0 stable version:      http://arduino.esp8266.com/stable/package_esp8266com_index.json

**Comment by roccomuso** [comment]
@tzapu Just discovered that if i move down the ESP8266WebServer.h dependency, in this way:

    #include <EEPROM.h>
    #include <WiFiClient.h>
    #include <DNSServer.h>
    #include <WiFiManager.h>
    #include <ESP8266WebServer.h>

I have no compile error.

**Comment by tzapu** [comment]
cool,
thanks for letting me know.

you can also remove 
```
#include <EEPROM.h>
#include <WiFiClient.h>
```
if you got the latest version of the lib. examples still need updating

**Comment by roccomuso** [comment]
@tzapu ok thank you.

**Comment by tzapu** [comment]
@roccomuso does it work ok with the 2.0.0 stable version?

**Comment by roccomuso** [comment]
@tzapu Tried today. It seems to work pretty well. :) I've tried it on a ESP866-01 board. And i've noticed that after the upload through the arduino ide (and GPIO0 pull down), you would get a <code>ets Jan  8 2013,rst cause:1, boot mode:(1,7)</code> error. So you must disconnect the pull down on GPIO0 and reset the board if you wanna make it works..

**Comment by tzapu** [comment]
hi, that s pretty much general for all esp8266 modules. otherwise they reboot back into firmware upload mode.

glad it s working, i ll close this then
