### PR TITLE
Update AutoConnectWithFSParameters to new ArduinoJson library

### LINKED ISSUE #654: ERROR when tried to complie  'DynamicJsonBuffer' was not declared in this scope
.I get the following error when i try to compile this code, can this be fixed its urgent, please lookinto it. 

Arduino: 1.8.5 (Linux), Board: "Generic ESP8266 Module, 80 MHz, ck, 26 MHz, 40MHz, QIO, 512K (no SPIFFS), v2 Prebuilt (MSS=536), Disabled, None, 115200"

/root/Arduino/Blink2/Blink2.ino: In function 'void setup()':
Blink2:51: error: 'DynamicJsonBuffer' was not declared in this scope
         DynamicJsonBuffer jsonBuffer;
         ^
/root/Arduino/Blink2/Blink2.ino:51:9: note: suggested alternative:
In file included from /root/Arduino/libraries/ArduinoJson/src/ArduinoJson/DynamicJsonDocument.hpp:10:0,
                 from /root/Arduino/libraries/ArduinoJson/src/ArduinoJson.hpp:9,
                 from /root/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:9,
                 from /root/Arduino/Blink2/Blink2.ino:10:
/root/Arduino/libraries/ArduinoJson/src/ArduinoJson/Memory/DynamicJsonBuffer.hpp:159:5: note:   'ArduinoJson::Internals::DynamicJsonBuffer'
     DynamicJsonBuffer;
     ^
Blink2:51: error: expected ';' before 'jsonBuffer'
         DynamicJsonBuffer jsonBuffer;
                           ^
Blink2:52: error: 'jsonBuffer' was not declared in this scope
         JsonObject& json = jsonBuffer.parseObject(buf.get());
                            ^
Blink2:53: error: 'class ArduinoJson::JsonObject' has no member named 'printTo'
         json.printTo(Serial);
              ^
Blink2:130: error: 'DynamicJsonBuffer' was not declared in this scope
     DynamicJsonBuffer jsonBuffer;
     ^
/root/Arduino/Blink2/Blink2.ino:130:5: note: suggested alternative:
In file included from /root/Arduino/libraries/ArduinoJson/src/ArduinoJson/DynamicJsonDocument.hpp:10:0,
                 from /root/Arduino/libraries/ArduinoJson/src/ArduinoJson.hpp:9,
                 from /root/Arduino/libraries/ArduinoJson/src/ArduinoJson.h:9,
                 from /root/Arduino/Blink2/Blink2.ino:10:
/root/Arduino/libraries/ArduinoJson/src/ArduinoJson/Memory/DynamicJsonBuffer.hpp:159:5: note:   'ArduinoJson::Internals::DynamicJsonBuffer'
     DynamicJsonBuffer;
     ^
Blink2:130: error: expected ';' before 'jsonBuffer'
     DynamicJsonBuffer jsonBuffer;
                       ^
Blink2:131: error: 'jsonBuffer' was not declared in this scope
     JsonObject& json = jsonBuffer.createObject();
                        ^
Blink2:141: error: 'class ArduinoJson::JsonObject' has no member named 'printTo'
     json.printTo(Serial);
          ^
Blink2:142: error: 'class ArduinoJson::JsonObject' has no member named 'printTo'
     json.printTo(configFile);
          ^
Multiple libraries were found for "ArduinoJson.h"
 Used: /root/Arduino/libraries/ArduinoJson
 Not used: /root/Arduino/libraries/ArduinoJson-master
exit status 1
'DynamicJsonBuffer' was not declared in this scope

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

### PR DESCRIPTION
**Pull request by jeroenrnl**
Fixes "DynamicJsonBuffer was not declared in this scope"

Works with ArduinoJson library 6.7.0beta (current version in library
manager)

Should fix #654

### CODE REVIEW

**Comment by tablatronix** [comment]
- [ ] apply to development sub feature branch
- [ ] alt make backwards compatible

**Comment by oxedgar** [comment]
Still waithing this enhancement too for the last stable version of arduinoJson library 6.10.1. 
Thankyou for your great job

**Comment by tablatronix** [comment]
This needs to be backward compatible either though compiler flags or a define

**Comment by ajobbins** [comment]
I've tested this, but it's failing with the later builds of ArduinoJson. It may have something to do with this:

> In older versions, DynamicJsonDocument was able to grow if needed. Starting with version 6.7.0, DynamicJsonDocument has a fixed capacity, just like StaticJsonDocument. This change allows better performance, smaller code, and no heap fragmentation.
> 
> Arduino 6.6.0 contained a full-blown allocator (i.e., non-monotonic) and was able to compact the memory inside the JsonDocument. This feature was reverted in version 6.7.0 because the overhead was unacceptable.
- https://arduinojson.org/v6/api/dynamicjsondocument/

**Comment by tablatronix** [comment]
yeah sounds like its going to be a pita, we will have to just update the example to 2 different versions for easier implementation.

**Comment by liebman** [comment]
I think that there may be a #define for the major version of ArduinoJson defined in the headers.  'ARDUINOJSON_VERSION_MAJOR' I think... Maybe it can be #ifdef'd to handle both?

**Comment by ajobbins** [comment]
Does it really need to be backward compatible with 5.x? Other projects I have seen aren't doing this and are simply updating to the new requirements of 6.x

**Comment by oxedgar** [comment]
I am currently adapting to AutoConnectWithFSParametersAndCustonIP.ino with version 6 and it is working properly. I just followed the upgrade guide available at ArduinoJson. However, I do not know if other items in the library are defective.

**Comment by tablatronix** [comment]
How long has 6 been stable for ? I thought it was a couple months

**Comment by ajobbins** [comment]
> How long has 6 been stable for ? I thought it was a couple months

Yes, looks like the first non-beta release was on March 2nd.

**Comment by Ruandv** [comment]
@tablatronix  this can be closed because of pull request #993

**Comment by tablatronix** [comment]
This PR looks clean, Might add some of this to #993, if it does not already have a nice wrapper func and error handling like this
