### ISSUE TITLE
compilation troubles

### ISSUE THREAD

**Issue by velectris** [tzapu/WiFiManager#12]
Hi,

Nice job !
i'm trying to compile on arduino ide 1.6.5 and have the following result 

Arduino: 1.6.5 (Windows 8.1), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 115200"

C:\Users\pascal\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp: In member function 'boolean WiFiManager::captivePortal()':
C:\Users\pascal\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:405:20: error: 'class ESP8266WebServer' has no member named 'hostHeader'
   if (!isIp(server.hostHeader()) ) {
                    ^
C:\Users\pascal\Documents\Arduino\libraries\WiFiManager-master\WiFiManager.cpp:407:82: error: 'class WiFiClient' has no member named 'localIP'
     server.sendHeader("Location", String("http://") + toStringIp(server.client().localIP()), true);
                                                                                  ^
Error compiling.

 Have you an idea of the real source of hostheader / localip compilation problem ? 

THX on advance for any help !
Cheers .

**Comment by tzapu** [comment]
hi, you need to install the staging version of the esp8266 for arduino ide package
https://github.com/esp8266/Arduino#staging-version-
let me know if it worked
cheers

**Comment by velectris** [comment]
Hi,

THX for this prompt answer !

Anyway, i have set-up the staging release in my ide, but i have exactly the
same compilation error...

I'm still interested in testing any other way to solve this issue, of
course.

Have a nice day !



Pascal Nuti
www.quantia.fr
www.solable.fr
https://www.linkedin.com/pub/pascal-nuti/17/82a/504

2015-11-17 9:00 GMT+01:00 tzapu <notifications@github.com>:

**Comment by tzapu** [comment]
hello,
could it be that you have multiple versions of the package or it s libraries from past installs? (hardware folder in arduino documents folder? past install of arduino package that included arduino ide as well?)
using staging fixed that error for everyone so far

cheers
alex

**Comment by tzapu** [comment]
glad it helped
good luck
